travis:
  secure:
    BINSTAR_TOKEN: 0ei1FxkDoFZ2YMJFQIxDMZKWSqDW3t/zLonKCfOJPTmF7sFuRjrTOUY9yqQbK144+sUpN6biDObgfEA5+n5rkZjO/u/T6h2lSi3UwC6xYQ0ap7osMTjEOpODX5wVVEe4UamT6+eCQT69wNkZX1jz83x+SlhhuTUXL6Nkf3CXO1uZo1S+8fd1j6S1dEXe5qQtBViLaE8TrebzG0J28T0xvh8YMEMZsGulECEZTfMzoV9pO6riyDrfrR2Vz5BKm/f1cFEeBFJyQUkx7KuluXkOGWA8vZxeg3o0vaS+bHJQAZkm+pfVto6tgotiDR3Stg+89i9CHxaiCMablc55NlM41Vfk/yk5Mo8XPHjsB2bJEO8PaTmdVgm7I9v4ILx4KAYBNDWLVOFUOxSh6FzB3HHizWQgnFe1xjUcIIAAX4TzM+CkiQFhZ5iO7lXaB9czIBo3M/Gj6xmN4SucBTbUeirpvstokTjWXkDQyVfBIxmzV622/h1s8sF87IEK4J8XBu+Et4ucpGKR+n4soIYfcqL1oueCK2jrz6xoEGc3QsDCCxXk9r+9sUapf/5yATrtl9LzywjSyNryXHW/ME0lgbsrYv2nJVbpIGt08CYhtkNHG9bGcsWJ3/aDG9ZP+uWfazkdWq1KTOXvS3yJ9zTuGmoUWpCyxZn1RDU/Cwi8WKGUUzo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
