travis:
  secure:
    BINSTAR_TOKEN: Hbwe8twueueIogvR32zhW5BdyEE0pwgwSlofwtLCFn0JLVOZqWDdlFumf5CrV47Nc6MHw/0tgLvNMf1yM/blrB1j3J9IMAZdI+goy9JWaoU5XCwC4FPHUVqocAb/0l0K1GVzv99zXNZilNASAGlz+aP6aK2I17PKXpFnmmyby5gtKkYZPODLgVdU35SO4aGyzVRmTlCAQ6rXtyCiJXZ+Iub2Ly9OZfMdf5+c3ejWDPB84e0htgwn7dxRkjDL5maHfaAtDxhiWDmveUkYqpePVMi1l3P7Tc2cBcmTeGLMuOaV1KMkKTdrVvGWoIsTjXlfUJpNJQ4WoXHQCoKyTrhBGS9W3nvWbNW3cVMi7CmivRjha5k2BPJ5GFx7PuWwuweOk/jvHdQhM/x4P2bxAaZVJG8tu4YoKzMFLI6KHZKL1hXGimQqOFkZt0sVXfHomiA4It4yoRW/mAIEI7x+jf0ZaPj8yK1xaC8LHH0MAcFm55Y0gTlWx8JMYWzyg4Qy1aBQsDnPealXydmGPv8eprzBbgJxy+5Kt8M215S1gkoMUXGbvGT21lcuKA0fb7V24/bPmZ63pUbvI94lM6c7Qxe1oy5hXqVA02xL/m100GHkWn0ql4zFmb/qEq6rftBG+iYw1KUyCSwIwy8rhGc0t19fNAQpTFmG3QNvrLoPTmMJtss=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
