travis:
  secure:
    BINSTAR_TOKEN: 2EpBe8B3qJaaZV/EwEf5aaDxXQcGw4oEwbTBB5bsbkCkFI9IAbpv7zEJEdOSK6uJXL0B0OlTSaDBsKMKy2DB8gDvkJ9Ah6AMz043tX8iM0viFo8gUv3FVM+LKEzcipFRanw0I/qzK881hR02e9N9rN22GeaWik6uQHO1Olws7ahTLVT+9vL7l6v5upxlilb1ZMk90nBG0KldS65KxnlyGalKZv2ul7i7eLqgdw8PINEVcjcaAeG7uliayx8/lrXKOLNwkj6NeyxoJKyM3oxiMOwxojfvvnihfp3S5Eud8LW81h+vfrTd2WE5QJ5plL5gOrsdYrW4+2NagRaXm3xk80rEwPh614ubPLU6eqFfx++1+bm0lG/ahaBC3dhiz8yk5RE4QFxw1gTNtnVqijFk4fThR8Tj2xPBUULYLsxFPy9KB7Cp4xsPJj5skvA3oh9l/KX6Xq2HyeBqE10xBMwN+f5QP0zRnGQsVDBSiW0fnpqRrieKstNwJamgAneW02OiBDrlemRQwFTLxvwazVui34AVJp/TyT0fkk+BE5uMxoZzHUlf8Sqjc5sGMxwzW0uvo7lJZ22wQTq+AgtiGH5gTSWH1bs6ecwybIhX+2pC1oGj2DrdoI6xVD+WcGYJTUyXbV5cpk0VCB/1wAv53kOD6P7YB7Go/VEARQ5YrCjXQKs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
